sudo: required
dist: xenial

addons:
  chrome: stable
  sonarcloud:
    organization: "sartography"
services:
  - xvfb
language: node_js

node_js:
  - 14

before_install:
  - dpkg --compare-versions `npm -v` ge 7.10 || npm i -g npm@^7.10
  - npm --version

before_script:
  - export DISPLAY=:99.0

install:
  - npm install

script:
  - npm run ci
  - sonar-scanner
